server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  application:
    name: ash-auth-service

#management:
#  endpoints:
#    enabled-by-default: false
#  endpoint:
#    shutdown:
#      enabled: true
#    info:
#      enabled: true
